apiVersion: v1
appVersion: "4.5.16"
description: Helm chart to deploy AppDynamics ClusterAgent for Kubernetes
name: appdynamics-cluster-agent
version: 20.7.0
home: https://www.appdynamics.com/
icon: https://raw.githubusercontent.com/Appdynamics/appdynamics-charts/master/logo.png
maintainers:
  - name: smangelkramer

keywords:
  - appdynamics
  - monitoring
  - Kubernetes
  - Rancher
