name: CI-push

on:
  push:
    branches:
      -  dev-v2.5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run CI scripts
      run: |-
        sudo make ci

    - uses: stefanzweifel/git-auto-commit-action@5c3c72f20e9a64b08dbca7257ca6d88ac7d07be8
      with:
        commit_message: Generated changes
        branch: dev-v2.5-assets
        file_pattern: assets/ index.html index.yaml
